var MESSAGES = {
    USERNAME_REQUIRED:'Username or Email is required.',
    USERNAME_EXIST:'Email or Username already exist.',
    USERNAME_NOT_FOUND:'Not found this Username or Email.',
    EMAIL_EXIST: 'This email id already registered.',
    USRNAME_EXIST:'Username already exist.',
    USER_REGISTER_SUCCESS: 'User registered successfully.',
    VERIFY_NEEDED: 'You need to verify your email then you can login.',
    SOMETHING_WAS_WRONG: 'Something went wrong.',
    SOCIAL_ID_EXIST: 'User already registered with us.',
    VISIBILITY_UPDATED: 'Visibility Updated.',
    VERIFY_EMAIL: 'Verification code is sent to your registered email.',
    OTP_REQ: 'OTP is required.',
    EMAIL_VERIFIED: 'Email Verified Successfully.',
    TOKEN_EXPIRED: 'Your Token has been expired.',
    DELETED_BY_ADMIN: 'Currently you have deactived by Admin.',
    LOGGED_IN_SUCCESS: 'User logged in successfully.',
    INVALID_PASSWORD: 'Invalid password',
    USER_NOT_EXIST: 'User not registered ',
    YOU_HAVE_REGISTERED_WITH_SOCIAL: 'You are Registered with Social Media Apps.',
    ENTER_REGISTERED_EMAIL: 'Please enter registered Email.',
    OTP_SENT_SUCCESS_MESSAGE: 'OTP sent successfully to your email address.',
    LOGGED_IN_FAILURE: 'Please enter correct credentials.',
    ENTER_VALID_EMAIL: 'Please enter valid email.' ,
    INVALID_OTP: 'Please enter valid OTP.',
    OTP_VERIFIED: 'OTP verified successfully.',
    OTP_EXPIRED: 'OTP Expired',
    PASSWORD: 'Please enter password.',
    PASSWORD_LENGTH: 'Password must be 8 digit at least.',
    PASSWORD_UPDATE_SUCCESS: 'Password updated successfully.',
    TOKEN_REQUIRED: 'Token field is required',
    INVALID_TOKEN: 'Invalid Token',
    LANGUAGE: 'language Updated.',
    UPLOADED_FILES: 'A Post is Created.',
    POST_LIST: 'Post List',
    SELECT_IMAGE: 'Please select image.' ,
    IMAGE_UPDATED: 'Profile image changed successfully.',
    RECORD_NOT_FOUND: 'Record not found.',
    RECORD_FOUND: 'Record found successfully.',
    INVALID_USER_ID: 'Please enter correct user id',
    LIKE_POST: 'liked a post',
    UNLIKE_POST: 'Unliked a post',
    POST_DELETED: 'Your post is removed',
    POST_SAVED: 'You Saved a Post',
    POST_UNSAVED: 'You removed a Post from save',
    SHARED_POST: 'You shared a Post',
    POST_UPDATED: 'Your Post Updated Successfully',
    LIKE_LIST: 'Your Post is Liked BY:',
    BIO_UPDATED: 'Info Updated Successfully.',
    POST_COMMENT: 'You commented on post.',
    COMMENT_LIST: 'Comments List',
    PROFILE_UPDATED: 'Profile Updated Successfully.',
    ADD_RESTAURANT: 'Restaurant Added to favourite',
    ADD_DISH: 'Dish Added to favourite',
    RESTAURANT_LIST: 'Favourite Restaurant List',
    DISH_LIST: 'Favourite Dish List',
    ADD_TO_FAV: 'Added to favourite',
    SAVED_POST_LIST: 'Saved Post List',
    USER_DETAILS: 'User Details',
    MOVIE_LIST: 'Movie List',
    TV_SHOWS_LIST: 'tv shows List',
    VIDEO_GAMES_LIST: 'Video games List',
    ADDED_TO_FAV_LIST: 'Added to favourite',
    LIST: 'List',
    RESTAURANT_DELETED:'Restaurant is removed from List',
    REMOVED_FROM_LIST: 'Removed from List',
    UPDATED_DISH: 'Dish is Updated Successfully',
    LOGOUT: 'Logout Successfully.',
    BUSSINESS_FAV: 'You favourited a Business',
    BUSSINESS_UNFAV: 'You Unfavoured a Business',
    FAV_LIST: 'Favourite List',
    REVIEW: 'Your Review is saved',
    NOTIFICATION_SETTING: 'Your Notification Setting is Updated',
    NOTIFICATION: 'Notification Setting',
    ADDED_COMMENT: 'added comment to a Post:',
    TOP_TEN_POST: 'Top Ten Post List',
    REVIEW_COMMENT: 'You commented on review.',
    LIKE_REVIEW: 'You Like a review',
    REVIEW_DETAILS: 'Review Details',
    RESTAURANT_EXISTS: 'Already Exists',
    TOP_TEN_RESTAURANTS: 'Top Ten Restaurants',
    TOP_TEN_MOVIES: 'Top Ten Movies',
    TOP_TEN_TVSHOW: 'Top Ten Tv shows',
    TOP_TEN_MUSIC: 'TOP Ten Musics',
    TOP_TEN_ARTIST: 'Top Ten Artists',
    TOP_TEN_GAMES: 'Top Ten Vediogames',
    SEARCH_LIST: 'Search List',
    REQUEST_SENT: 'You send a Request to follow',
    REQUEST_ACCEPTED: 'You accepted a request',
    REQUEST_DECLINE: 'You decline a request',
    REQUEST_SENT__ALREADY: 'You have already sent a request',
    NOTIFICATION_LIST: 'List Of Notifications',
    NOTIFICATION_READ: "Notifications Read",
    PRIVATE_ACCOUNT: 'This Profile is Private, follow to see more',
    NOT_A_DISH: "not a dish",
    BLOCK_USER: 'You Block this User ',
    UNBLOCK_USER: 'You Unblock this User',
    BLOCK_PROFILE: 'Block Profile',
    ALREADY_BLOCK_USER: 'Already block this User',
    FOLLOW_REQUEST: 'You have a new follow request',
    NEW_FOLLOWER: 'You have a new follower',
    START_FOLLOW: 'You start to follow',
    UNLIKE_REVIEW: 'You Unlike a Review',
    ADDED_POST: 'added a new',
    POST: 'post',
    PHOTO: 'photo',
    VEDIO: 'vedio',
    LIKE_DISH: 'You Like a Dish',
    UNLIKE_DISH: 'You Unlike a Dish',
    COMMENT_DISH : 'You commented on Dish',
    DISH_DETAILS: 'Dish Details',
    DISH_ADDED_BYOTHERS: 'Dishes that were Already Submitted By Other Users',
    REVIEW_ON_DISH: 'Review on Dish',
    NO_IMAGES: 'Upload Images First',
    TEN_DATA_ALREADY: 'You have already saved ten in your list. Delete to Add new',
    DRAG_N_DROP: 'Succesfully Updated the Sequence',
    NEW : 'New #1 in category',
    RESTAURANT: 'Restaurants'
    
    
    // PASSWORD_CHANGE_SUCCESS: 'Password changed successfully.',
   
    
    
};
module.exports = MESSAGES;
